misc: smc_cpld: fix compile error on the .remove callback
An error can be found while compiling develop-6.1.15 with CONFIG_SMC_LEGOC2_CPLD=y:

/openbmc/build/legoc2/tmp/work-shared/legoc2/kernel-source/drivers/misc/smc_cpld/smc_cpld.c: In function 'smc_cpld_probe':
/openbmc/build/legoc2/tmp/work-shared/legoc2/kernel-source/drivers/misc/smc_cpld/smc_cpld.c:290:13: warning: unused variable 'ret' [-Wunused-variable]
  290 |         int ret = 0;
      |             ^~~
/openbmc/build/legoc2/tmp/work-shared/legoc2/kernel-source/drivers/misc/smc_cpld/smc_cpld.c: At top level:
/openbmc/build/legoc2/tmp/work-shared/legoc2/kernel-source/drivers/misc/smc_cpld/smc_cpld.c:326:19: error: initialization of 'void (*)(struct i2c_client *)' from incompatible point
  326 |         .remove = smc_cpld_remove,
      |                   ^~~~~~~~~~~~~~~
/openbmc/build/legoc2/tmp/work-shared/legoc2/kernel-source/drivers/misc/smc_cpld/smc_cpld.c:326:19: note: (near initialization for 'smc_cpld_driver.remove')
  CC      drivers/dma-buf/dma-fence-unwrap.o
  CC      fs/filesystems.o
cc1: some warnings being treated as errors
make[4]: *** [/openbmc/build/legoc2/tmp/work-shared/legoc2/kernel-source/scripts/Makefile.build:250: drivers/misc/smc_cpld/smc_cpld.o] Error 1
make[3]: *** [/openbmc/build/legoc2/tmp/work-shared/legoc2/kernel-source/scripts/Makefile.build:500: drivers/misc/smc_cpld] Error 2
make[2]: *** [/openbmc/build/legoc2/tmp/work-shared/legoc2/kernel-source/scripts/Makefile.build:500: drivers/misc] Error 2

Here we have to fix the return type of smc_cpld_remove() because the .remove
callback of the struct i2c_driver has been changed since the upstream patch
ed5c2f5fd10dda0.

In the meanwhile, the ret variable is unused so let's remove it from
smc_cpld_probe().

Signed-off-by: Chester Lin <chesterl@nvidia.com>