misc: quanta_cpld: fix compile error on the .remove callback
An error can be found while compiling develop-6.1.15 with CONFIG_QUANTA_LEGOCG1_CPLD=y:

  /legocg1/workspace/sources/linux-aspeed/drivers/misc/quanta_cpld/quanta_cpld.c: In function 'quanta_cpld_is_visible':
  /legocg1/workspace/sources/linux-aspeed/drivers/misc/quanta_cpld/quanta_cpld.c:136:21: warning: unused variable 'virt' [-Wunused-variable]
    136 |                 int virt = channel >> 1;
        |                     ^~~~
  /legocg1/workspace/sources/linux-aspeed/drivers/misc/quanta_cpld/quanta_cpld.c: At top level:
  /legocg1/workspace/sources/linux-aspeed/drivers/misc/quanta_cpld/quanta_cpld.c:331:19: error: initialization of 'void (*)(struct i2c_client *)'     from incompatible pointer type 'int (*)(struct i2c_c  331 |         .remove = quanta_cpld_remove,
        |                   ^~~~~~~~~~~~~~~~~~
  /legocg1/workspace/sources/linux-aspeed/drivers/misc/quanta_cpld/quanta_cpld.c:331:19: note: (near initialization for 'quanta_cpld_driver.remove')
  cc1: some warnings being treated as errors

Here we have to fix the return type of quanta_cpld_remove() because the .remove
callback of the struct i2c_driver has been changed since the upstream patch
ed5c2f5fd10dda0.

In the meanwhile, the virt variable is unused so let's remove it from
quanta_cpld_is_visible().

Signed-off-by: Chester Lin <chesterl@nvidia.com>